name: Load Test

on:
  workflow_call:

jobs:

  loadtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurando credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Clonando repositório Infra_CI
        run: git clone https://github.com/abatistas1709/Infra_CI

      - name: HashiCorp - Setup terraform
        uses: hashicorp/setup-terraform@v2.0.3

      # - name: Limpa o cache de módulos do Terraform
      #   run: rm -rf .terraform && rm -f .terraform.lock.hcl

      - name: Inicializando Terraform
        run: terraform -chdir=Infra_CI/env/Homolog init

      - name: Destruindo ambiente existente
        run: terraform -chdir=Infra_CI/env/Homolog destroy -auto-approve

      - name: Aplicando configuração Terraform
        run: terraform -chdir=Infra_CI/env/Homolog apply -auto-approve

      - name: Obtendo IP do ALB
        id: URL
        run: echo "$(terraform -chdir=Infra_CI/env/Homolog output -raw IP_alb)"

      - name: Setup Python
        uses: actions/setup-python@v2.3.3
        with:
          python-version: "3.10"

      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            locust

      - run: |
          echo "from locust import HttpUser, TaskSet, task, between" >> locustfile.py
          echo "" >> locustfile.py
          echo "class UserTasks(TaskSet):" >> locustfile.py
          echo "  @task(1)" >> locustfile.py
          echo "  def index(self):" >> locustfile.py
          echo '    self.client.get("/bruno")' >> locustfile.py
          echo "" >> locustfile.py
          echo "class WebsiteUser(HttpUser)" >> locustfile.py
          echo "  tasks = [UserTasks]" >> locustfile.py
          echo "  wait_time = between(1, 5)" >> locustfile.py

      - name: Roda teste de carga
        run: sleep 60s ; locust -f locustfile.py --headless -u 10 -r 5 --run-time 60s -H http://${{ steps.URL.outputs.stdout }}

      - name: Destruindo ambiente existente
        run: terraform -chdir=Infra_CI/env/Homolog destroy -auto-approve